In [ ]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [ ]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.data_max_)
print(scaler.data_min_)

MinMaxScaler(copy=True, feature_range=(0, 1))
[ 1. 18.]
[-1.  2.]


In [ ]:
#https://m.blog.naver.com/PostView.nhn?blogId=wideeyed&logNo=221614354947&proxyReferer=https:%2F%2Fwww.google.com%2F

In [ ]:
data2 = [[-5, 25]]
scaler.partial_fit(data2)
print(scaler.data_max_)
print(scaler.data_min_)

[ 1. 25.]
[-5.  2.]


In [ ]:
print(scaler.transform(data))
print(scaler.transform(data2))

[[0.66666667 0.        ]
 [0.75       0.17391304]
 [0.83333333 0.34782609]
 [1.         0.69565217]]
[[0. 1.]]


In [ ]:
#https://datascienceschool.net/view-notebook/f43be7d6515b48c0beb909826993c856/

In [ ]:
import numpy as np
data3 = [-10, 30]
print(data3)

data3 = np.array(data3).reshape(-1, 2)
scaler.partial_fit(data3)
print(data3)
print(scaler.data_max_)
print(scaler.data_min_)
print(scaler.transform(data3))

print(data3[0])

[-10, 30]
[[-10  30]]
[30. 30.]
[-10. -10.]
[[0. 1.]]
[-10]


In [ ]:
data4 = [1,2,3,4,5]
scaler = MinMaxScaler()
data4 = np.array(data4).reshape(-1, 1)
print(data4)

scaler.fit(data4)
print(scaler.transform(data4))

print(data4[:10, 0])
print(np.array(data4[:, 0]))
print(np.array(data4[:, 0])[:10])

[[1]
 [2]
 [3]
 [4]
 [5]]
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
