In [0]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
from google.colab import files

tf.set_random_seed(777)  # for reproducibility

In [7]:
#파일업로드창 출력
uploaded = files.upload()

#업로드한 파일정보 출력
for fn in uploaded.keys():
  print('Upload file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))

Saving data-01-test-score.csv to data-01-test-score.csv
Upload file "data-01-test-score.csv" with length 325 bytes


In [8]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [9]:


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

Instructions for updating:
Colocations handled automatically by placer.


In [12]:

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 500 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 21027.0 
Prediction:
 [[22.048063 ]
 [21.619785 ]
 [24.096693 ]
 [22.293016 ]
 [18.633898 ]
 [ 7.2669706]
 [12.331034 ]
 [ 3.1505105]
 [14.347936 ]
 [ 4.2534266]
 [14.485711 ]
 [10.678065 ]
 [28.804642 ]
 [29.298807 ]
 [11.237835 ]
 [18.64654  ]
 [31.189459 ]
 [13.344662 ]
 [28.84174  ]
 [25.662813 ]
 [15.084752 ]
 [16.798367 ]
 [15.924548 ]
 [31.361118 ]
 [24.986366 ]]
500 Cost: 65.93824 
Prediction:
 [[156.79225 ]
 [185.3289  ]
 [184.4181  ]
 [197.83768 ]
 [143.14839 ]
 [100.726616]
 [144.64084 ]
 [102.454926]
 [168.90562 ]
 [149.6524  ]
 [141.51567 ]
 [137.06999 ]
 [193.50372 ]
 [164.98135 ]
 [144.52289 ]
 [185.50893 ]
 [159.81026 ]
 [172.31714 ]
 [185.43796 ]
 [165.75996 ]
 [170.15598 ]
 [171.18742 ]
 [163.35484 ]
 [165.03453 ]
 [193.93121 ]]
1000 Cost: 46.333588 
Prediction:
 [[155.79347 ]
 [185.46011 ]
 [183.79823 ]
 [197.92883 ]
 [142.94722 ]
 [101.916466]
 [145.47525 ]
 [104.105225]
 [170.27351 ]
 [152.73248 ]
 [141.92949 ]
 [138.35954 ]
 [192.1013  ]
 [162.8083  ]
 [14