In [0]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [0]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

#x_data shape: [8,4] y_data shape: [8,3]

In [0]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3   #softmax에서 구분할 class 갯수 (y의 출력값)

In [8]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight') #weight: 입력4, 출력3(class)
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')      #bias  : 출력3(class)

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [0]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1)) # 수식에 맞춰서 계산

In [11]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost) # 경사하강법으로 cost를 최적

Instructions for updating:
Use tf.cast instead.


In [15]:

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # trainig
    for step in range(2001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)
              
    # 최적화된 w,b에 대한 hypothesis를 가지고 테스트 진      
    # Testing & One-hot encoding
    print('--------------')
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})   #test data 입력
    print(a, sess.run(tf.argmax(a, 1)))                        #softmax결과값에서 최대값을 출

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1))) # [1 0 2]

0 6.926112
200 0.6005015
400 0.47295794
600 0.3734296
800 0.28018382
1000 0.23280518
1200 0.21065344
1400 0.19229898
1600 0.17682318
1800 0.16359559
2000 0.15216145
--------------
[[1.3890372e-03 9.9860197e-01 9.0613012e-06]] [1]
--------------
[[0.93119216 0.062902   0.0059059 ]] [0]
--------------
[[1.2732767e-08 3.3411290e-04 9.9966586e-01]] [2]
--------------
[[1.3890372e-03 9.9860197e-01 9.0613012e-06]
 [9.3119216e-01 6.2902004e-02 5.9058964e-03]
 [1.2732768e-08 3.3411290e-04 9.9966586e-01]] [1 0 2]
