In [0]:
import numpy as np
from sklearn import linear_model


In [3]:
np.random.seed(0)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]

#y_data = [[0, 0, 1], 
#          [0, 0, 1],
#          [0, 0, 1],
#          [0, 1, 0],
#          [0, 1, 0],
#          [0, 1, 0],
#          [1, 0, 0],
#          [1, 0, 0]]

y_data = [2, 2, 2, 1, 1, 1, 0, 0]

#x_data shape: [8,4] y_data shape: [8,3] (0,1,2 class) -> [8, ] 1차원 array로 결과값만 사용
print("x_data.shape:", np.array(x_data).shape, "y_data.shape:", np.array(y_data).shape)

x_data.shape: (8, 4) y_data.shape: (8,)


In [8]:
softmax_reg = linear_model.LogisticRegression(multi_class="multinomial", solver="lbfgs", C=10) #C:Hyper parameter for regularization
result = softmax_reg.fit(x_data, y_data)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [9]:
Class = softmax_reg.predict(x_data)
prob = softmax_reg.predict_proba(x_data)
print("Class:", Class, "prob:", prob)

Class: [2 2 2 1 1 1 0 0] prob: [[2.08296417e-13 7.94686715e-05 9.99920531e-01]
 [2.80855884e-09 6.98567371e-03 9.93014323e-01]
 [8.09080598e-07 8.74583320e-02 9.12540859e-01]
 [2.37192094e-03 9.33723156e-01 6.39049233e-02]
 [1.46372059e-01 8.48657157e-01 4.97078393e-03]
 [4.70818357e-02 9.27417110e-01 2.55010547e-02]
 [8.07256015e-01 1.92643828e-01 1.00157131e-04]
 [9.96944467e-01 3.05548594e-03 4.75352729e-08]]


In [11]:
x_test = [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]
Class = softmax_reg.predict(x_test)
prob = softmax_reg.predict_proba(x_test)
print("Class:", Class, "prob:", prob)

# 06_1_softmax_classifier.ipynb의 test data 결과가 다름;; 일단 pass

Class: [0 2 2] prob: [[9.99989812e-01 1.01875727e-05 1.72826590e-12]
 [1.68707181e-05 2.36489216e-01 7.63493913e-01]
 [1.39869488e-15 7.67730406e-06 9.99992323e-01]]
