In [0]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

In [2]:
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

print(xy.shape)

(8, 5)


In [0]:
#In [6]: X_MinMax = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
#참고: https://rfriend.tistory.com/270
def min_max_scaler(data):
    print("np.min(data, 0):", np.min(data, 0))
    
    numerator = data - np.min(data, 0)
    print("numerator:", numerator)
    
    print("np.max(data, 0):", np.max(data, 0))
    denominator = np.max(data, 0) - np.min(data, 0)
    print("denominator:", denominator)
    
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [5]:
# very important. It does not work without it.
xy = min_max_scaler(xy)
print("xy:", xy)

np.min(data, 0): [0. 0. 0. 0. 0.]
numerator: [[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
np.max(data, 0): [0.99999999 0.99999999 1.         1.         1.        ]
denominator: [0.99999999 0.99999999 1.         1.         1.        ]
xy: [[0.9999999  0.9999999  0.         0.9999999  0.9999999 ]
 [0.70548484 0.70439545 0.9999999  0.71881775 0.83755783]
 [0.54412544 0.50274819 0.5760869  0.60646794 0.66063303]
 [0.33890349 0.3136802  0.10869564 0.4598913  0.43800914]
 [0.51435995 0.42582385 0.3043478  0.585048   0.42624397]
 [0.49556174 0.42582385 0.31521736 0.48131129 0.4927

In [6]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)
print(y_data)

(8, 4) (8, 1)
[[0.9999999 ]
 [0.83755783]
 [0.66063303]
 [0.43800914]
 [0.42624397]
 [0.49276132]
 [0.18597236]
 [0.        ]]


In [0]:

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [0]:

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 20 == 0 :
      print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.15230924 
Prediction:
 [[ 1.634619  ]
 [ 0.06613705]
 [ 0.35008183]
 [ 0.6707252 ]
 [ 0.61130756]
 [ 0.6146441 ]
 [ 0.2317197 ]
 [-0.1372836 ]]
20 Cost:  0.15229823 
Prediction:
 [[ 1.6345959 ]
 [ 0.06616578]
 [ 0.35009497]
 [ 0.6707213 ]
 [ 0.61130923]
 [ 0.6146474 ]
 [ 0.23172614]
 [-0.13725987]]
40 Cost:  0.15228717 
Prediction:
 [[ 1.6345725 ]
 [ 0.0661945 ]
 [ 0.35010815]
 [ 0.67071736]
 [ 0.61131096]
 [ 0.6146507 ]
 [ 0.23173258]
 [-0.13723621]]
60 Cost:  0.15227611 
Prediction:
 [[ 1.6345494 ]
 [ 0.06622335]
 [ 0.35012132]
 [ 0.67071354]
 [ 0.6113127 ]
 [ 0.614654  ]
 [ 0.23173901]
 [-0.13721254]]
80 Cost:  0.15226506 
Prediction:
 [[ 1.634526  ]
 [ 0.0662522 ]
 [ 0.35013443]
 [ 0.6707096 ]
 [ 0.6113144 ]
 [ 0.6146573 ]
 [ 0.23174545]
 [-0.13718894]]
100 Cost:  0.15225405 
Prediction:
 [[ 1.6345029 ]
 [ 0.06628096]
 [ 0.3501476 ]
 [ 0.67070574]
 [ 0.61131614]
 [ 0.6146606 ]
 [ 0.23175189]
 [-0.13716522]]
