In [0]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [3]:
#Simple Array
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

[0. 1. 2. 3. 4. 5. 6.]
array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [4]:
#2D Array
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [11]:
#Shape, Rank, Axis
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4], dtype=int32)

In [13]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [14]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [15]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [21]:
#Matmul VS multiply
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(matrix1.shape)
print(matrix2.shape)
new_matrix  = tf.matmul(matrix1, matrix2).eval()
print(new_matrix.shape)
new_matrix

(1, 2)
(2, 1)
(1, 1)


array([[12.]], dtype=float32)

In [22]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

In [23]:
#Watch out broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [24]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

In [25]:
#Random values for variable initializations
tf.random_normal([3]).eval()

array([ 1.440054  ,  1.16297   , -0.31883723], dtype=float32)

In [26]:
tf.random_uniform([2]).eval()

array([0.93552196, 0.70838475], dtype=float32)

In [27]:
tf.random_uniform([2, 3]).eval()

array([[0.1764034 , 0.5726155 , 0.50345874],
       [0.4271766 , 0.76786315, 0.2733215 ]], dtype=float32)

In [39]:
#Reduce Mean/Sum
#평균값과 합계(특정 열을 기준으로 처리가)
#axis=0 > Y축(열), axis=1>X축()

# 1 ???
tf.reduce_mean([1, 2], axis=0).eval()

1

In [30]:
x = [[1., 2.],
     [3., 4.]]
#전체 평
tf.reduce_mean(x).eval()

2.5

In [31]:
#열에서의 평균 
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [35]:
#행에서의 평균
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [40]:
tf.reduce_sum(x).eval()

10.0

In [41]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [45]:
#axis=-1, 가장 안쪽에 있는 값들의 평균
print(x)
x2 = tf.reduce_sum(x, axis=-1).eval()
print(x2)

[[1.0, 2.0], [3.0, 4.0]]
[3. 7.]


In [43]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [46]:
#Argmax with axis
#tf.argmax(X, a) : X 배열에서 가장 큰 값을 ‘열(1)’ 기준 몇번째인지 index를 반환
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [47]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [48]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

In [49]:
#Reshape, squeeze, expand_dims
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [50]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [52]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [53]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [54]:
#One hot
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [55]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [56]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [57]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

In [58]:
#Stack
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [59]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [60]:
#Ones like and Zeros like
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [61]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [62]:
#Zip
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6
