In [3]:
#https://keras.io/getting-started/functional-api-guide/
#First example: a densely-connected network

from keras.layers import Input, Dense
from keras.models import Model
from keras.layers import TimeDistributed

# Input tensor for sequences of 20 timesteps,
# each containing a 784-dimensional vector
input_sequences = Input(shape=(20, 784))
print(input_sequences.shape)
#(?, 20, 784)

# a layer instance is callable on a tensor, and returns a tensor
output_1 = Dense(64, activation='relu')(input_sequences)
print(output_1.shape)
#

output_2 = Dense(64, activation='relu')(output_1)
print(output_2.shape)

predictions = Dense(10, activation='softmax')(output_2)
print(predictions.shape)
#(?, 20, 784)

# This creates a model that includes
# the Input layer and three Dense layers
model = Model(inputs=input_sequences, outputs=predictions)

# This applies our previous model to every timestep in the input sequences.
# the output of the previous model was a 10-way softmax,
# so the output of the layer below will be a sequence of 20 vectors of size 10.
processed_sequences = TimeDistributed(model)(input_sequences)
print(processed_sequences.shape)
#(?, 20, 784)

model.summary()

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

(?, 20, 784)

(?, 20, 64)
(?, 20, 64)
(?, 20, 10)
(?, 20, 10)
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 20, 784)           0         
_________________________________________________________________
dense_2 (Dense)              (None, 20, 64)            50240     
_________________________________________________________________
dense_3 (Dense)              (None, 20, 64)            4160      
_________________________________________________________________
dense_4 (Dense)              (None, 20, 10)            650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________




In [11]:
import numpy as np

data = np.array([[range(784) for _ in range(20)]]) 
print(data)
print(data.shape) #(1, 20, 784)
labels = np.array([[range(10) for _ in range(20)]])
print(labels.shape) #(1, 20, 10)
print(labels)

model.fit(data, labels)  # starts training

[[[  0   1   2 ... 781 782 783]
  [  0   1   2 ... 781 782 783]
  [  0   1   2 ... 781 782 783]
  ...
  [  0   1   2 ... 781 782 783]
  [  0   1   2 ... 781 782 783]
  [  0   1   2 ... 781 782 783]]]
(1, 20, 784)
(1, 20, 10)
[[[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]]
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/1





1/1 [==============================] - 5s 5s/step - loss: 644.7238 - acc: 0.0000e+00
